// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentPortal.Api.Data;


#nullable disable

namespace StudentPortalApi.Migrations
{
    [DbContext(typeof(StudentPortalDbContext))]
    [Migration("20251116101223_SeedAttendance")]
    partial class SeedAttendance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AttendanceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttendanceId")
                        .HasColumnType("int");

                    b.Property<int>("ClassType")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AttendanceId");

                    b.ToTable("AttendanceRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AttendanceId = 1,
                            ClassType = 0,
                            Date = new DateTime(2025, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Remarks = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            AttendanceId = 1,
                            ClassType = 0,
                            Date = new DateTime(2025, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            AttendanceId = 1,
                            ClassType = 0,
                            Date = new DateTime(2025, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            AttendanceId = 1,
                            ClassType = 0,
                            Date = new DateTime(2025, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Remarks = "Arrived 10 minutes late",
                            Status = 2
                        },
                        new
                        {
                            Id = 5,
                            AttendanceId = 1,
                            ClassType = 0,
                            Date = new DateTime(2025, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            AttendanceId = 1,
                            ClassType = 0,
                            Date = new DateTime(2025, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Remarks = "Medical leave",
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            AttendanceId = 1,
                            ClassType = 0,
                            Date = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 8,
                            AttendanceId = 1,
                            ClassType = 0,
                            Date = new DateTime(2025, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 9,
                            AttendanceId = 1,
                            ClassType = 0,
                            Date = new DateTime(2025, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 10,
                            AttendanceId = 1,
                            ClassType = 0,
                            Date = new DateTime(2025, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 11,
                            AttendanceId = 1,
                            ClassType = 0,
                            Date = new DateTime(2025, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 12,
                            AttendanceId = 1,
                            ClassType = 0,
                            Date = new DateTime(2025, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 13,
                            AttendanceId = 1,
                            ClassType = 0,
                            Date = new DateTime(2025, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 14,
                            AttendanceId = 1,
                            ClassType = 0,
                            Date = new DateTime(2025, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 15,
                            AttendanceId = 1,
                            ClassType = 0,
                            Date = new DateTime(2025, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 16,
                            AttendanceId = 1,
                            ClassType = 0,
                            Date = new DateTime(2025, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 17,
                            AttendanceId = 1,
                            ClassType = 0,
                            Date = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 18,
                            AttendanceId = 1,
                            ClassType = 0,
                            Date = new DateTime(2025, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 19,
                            AttendanceId = 1,
                            ClassType = 0,
                            Date = new DateTime(2025, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 20,
                            AttendanceId = 1,
                            ClassType = 0,
                            Date = new DateTime(2025, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 21,
                            AttendanceId = 2,
                            ClassType = 1,
                            Date = new DateTime(2025, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 22,
                            AttendanceId = 2,
                            ClassType = 1,
                            Date = new DateTime(2025, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 23,
                            AttendanceId = 2,
                            ClassType = 1,
                            Date = new DateTime(2025, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Remarks = "Personal emergency",
                            Status = 1
                        },
                        new
                        {
                            Id = 24,
                            AttendanceId = 2,
                            ClassType = 1,
                            Date = new DateTime(2025, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 25,
                            AttendanceId = 2,
                            ClassType = 1,
                            Date = new DateTime(2025, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Remarks = "Arrived 15 minutes late",
                            Status = 2
                        },
                        new
                        {
                            Id = 26,
                            AttendanceId = 2,
                            ClassType = 1,
                            Date = new DateTime(2025, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 27,
                            AttendanceId = 2,
                            ClassType = 1,
                            Date = new DateTime(2025, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 28,
                            AttendanceId = 2,
                            ClassType = 1,
                            Date = new DateTime(2025, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 29,
                            AttendanceId = 2,
                            ClassType = 1,
                            Date = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 30,
                            AttendanceId = 2,
                            ClassType = 1,
                            Date = new DateTime(2025, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 31,
                            AttendanceId = 2,
                            ClassType = 1,
                            Date = new DateTime(2025, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 32,
                            AttendanceId = 2,
                            ClassType = 1,
                            Date = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Remarks = "Official university event",
                            Status = 3
                        },
                        new
                        {
                            Id = 33,
                            AttendanceId = 2,
                            ClassType = 1,
                            Date = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 34,
                            AttendanceId = 2,
                            ClassType = 1,
                            Date = new DateTime(2025, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 35,
                            AttendanceId = 2,
                            ClassType = 1,
                            Date = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 36,
                            AttendanceId = 2,
                            ClassType = 1,
                            Date = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 37,
                            AttendanceId = 2,
                            ClassType = 1,
                            Date = new DateTime(2025, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 38,
                            AttendanceId = 2,
                            ClassType = 1,
                            Date = new DateTime(2025, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 39,
                            AttendanceId = 3,
                            ClassType = 0,
                            Date = new DateTime(2025, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 40,
                            AttendanceId = 3,
                            ClassType = 0,
                            Date = new DateTime(2025, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 41,
                            AttendanceId = 3,
                            ClassType = 0,
                            Date = new DateTime(2025, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 42,
                            AttendanceId = 3,
                            ClassType = 0,
                            Date = new DateTime(2025, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 43,
                            AttendanceId = 3,
                            ClassType = 0,
                            Date = new DateTime(2025, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 44,
                            AttendanceId = 3,
                            ClassType = 0,
                            Date = new DateTime(2025, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 45,
                            AttendanceId = 3,
                            ClassType = 0,
                            Date = new DateTime(2025, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 46,
                            AttendanceId = 3,
                            ClassType = 0,
                            Date = new DateTime(2025, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 47,
                            AttendanceId = 3,
                            ClassType = 0,
                            Date = new DateTime(2025, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 48,
                            AttendanceId = 3,
                            ClassType = 0,
                            Date = new DateTime(2025, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 49,
                            AttendanceId = 3,
                            ClassType = 0,
                            Date = new DateTime(2025, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 50,
                            AttendanceId = 3,
                            ClassType = 0,
                            Date = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 51,
                            AttendanceId = 3,
                            ClassType = 0,
                            Date = new DateTime(2025, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 52,
                            AttendanceId = 3,
                            ClassType = 0,
                            Date = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 53,
                            AttendanceId = 3,
                            ClassType = 0,
                            Date = new DateTime(2025, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 54,
                            AttendanceId = 3,
                            ClassType = 0,
                            Date = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 55,
                            AttendanceId = 4,
                            ClassType = 0,
                            Date = new DateTime(2025, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 56,
                            AttendanceId = 4,
                            ClassType = 0,
                            Date = new DateTime(2025, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Remarks = "Missed class",
                            Status = 1
                        },
                        new
                        {
                            Id = 57,
                            AttendanceId = 4,
                            ClassType = 0,
                            Date = new DateTime(2025, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 58,
                            AttendanceId = 4,
                            ClassType = 0,
                            Date = new DateTime(2025, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 59,
                            AttendanceId = 4,
                            ClassType = 0,
                            Date = new DateTime(2025, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 60,
                            AttendanceId = 4,
                            ClassType = 0,
                            Date = new DateTime(2025, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Remarks = "Medical appointment",
                            Status = 1
                        },
                        new
                        {
                            Id = 61,
                            AttendanceId = 4,
                            ClassType = 0,
                            Date = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Remarks = "Arrived 20 minutes late",
                            Status = 2
                        },
                        new
                        {
                            Id = 62,
                            AttendanceId = 4,
                            ClassType = 0,
                            Date = new DateTime(2025, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 63,
                            AttendanceId = 4,
                            ClassType = 0,
                            Date = new DateTime(2025, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 64,
                            AttendanceId = 4,
                            ClassType = 0,
                            Date = new DateTime(2025, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 65,
                            AttendanceId = 4,
                            ClassType = 0,
                            Date = new DateTime(2025, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 66,
                            AttendanceId = 4,
                            ClassType = 0,
                            Date = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 67,
                            AttendanceId = 4,
                            ClassType = 0,
                            Date = new DateTime(2025, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 68,
                            AttendanceId = 4,
                            ClassType = 0,
                            Date = new DateTime(2025, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 69,
                            AttendanceId = 4,
                            ClassType = 0,
                            Date = new DateTime(2025, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 70,
                            AttendanceId = 4,
                            ClassType = 0,
                            Date = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 71,
                            AttendanceId = 4,
                            ClassType = 0,
                            Date = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 72,
                            AttendanceId = 4,
                            ClassType = 0,
                            Date = new DateTime(2025, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 73,
                            AttendanceId = 4,
                            ClassType = 0,
                            Date = new DateTime(2025, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 74,
                            AttendanceId = 4,
                            ClassType = 0,
                            Date = new DateTime(2025, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        });
                });

            modelBuilder.Entity("CourseSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("CourseSchedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            Day = "Monday",
                            EndTime = "11:30",
                            Location = "Room 301",
                            StartTime = "10:00"
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 1,
                            Day = "Wednesday",
                            EndTime = "11:30",
                            Location = "Room 301",
                            StartTime = "10:00"
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 2,
                            Day = "Tuesday",
                            EndTime = "15:30",
                            Location = "Lab 205",
                            StartTime = "14:00"
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 2,
                            Day = "Thursday",
                            EndTime = "15:30",
                            Location = "Lab 205",
                            StartTime = "14:00"
                        });
                });

            modelBuilder.Entity("Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ContactNumber");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateOfBirth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("EnrollmentDate");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FirstName");

                    b.Property<double>("GPA")
                        .HasColumnType("float")
                        .HasColumnName("GPA");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LastName");

                    b.Property<string>("Major")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Major");

                    b.Property<string>("ProfileImage")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("ProfileImage");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("StudentId");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactNumber = "+230-5123-4567",
                            DateOfBirth = new DateTime(2003, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tirthesh.parbutee@university.mu",
                            EnrollmentDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Tirthesh",
                            GPA = 3.75,
                            LastName = "Parbutee",
                            Major = "Computer Science",
                            ProfileImage = "/assets/images/default-avatar.png",
                            StudentId = "CS202101",
                            Year = 3
                        });
                });

            modelBuilder.Entity("StudentPortalApi.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("City");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Country");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("State");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Street");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ZipCode");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Reduit",
                            Country = "Mauritius",
                            State = "Moka",
                            Street = "123 University Street",
                            StudentId = 1,
                            ZipCode = "80837"
                        });
                });

            modelBuilder.Entity("StudentPortalApi.Models.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("EarnedScore")
                        .HasColumnType("float");

                    b.Property<string>("Feedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GradeId")
                        .HasColumnType("int");

                    b.Property<double>("MaxScore")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmittedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("GradeId");

                    b.ToTable("Assignments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DueDate = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EarnedScore = 92.0,
                            Feedback = "Excellent work on implementing the Factory pattern!",
                            GradeId = 1,
                            MaxScore = 100.0,
                            Name = "Design Patterns Assignment",
                            Status = 2,
                            SubmittedDate = new DateTime(2025, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Weight = 20.0
                        });
                });

            modelBuilder.Entity("StudentPortalApi.Models.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AttendancePercentage")
                        .HasColumnType("float")
                        .HasColumnName("AttendancePercentage");

                    b.Property<int>("AttendedClasses")
                        .HasColumnType("int")
                        .HasColumnName("AttendedClasses");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CourseCode");

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("CourseId");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("CourseName");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentId");

                    b.Property<int>("TotalClasses")
                        .HasColumnType("int")
                        .HasColumnName("TotalClasses");

                    b.HasKey("Id");

                    b.ToTable("Attendances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AttendancePercentage = 95.0,
                            AttendedClasses = 19,
                            CourseCode = "CSE-4101",
                            CourseId = 1,
                            CourseName = "Advanced Software Engineering",
                            Status = 0,
                            StudentId = 1,
                            TotalClasses = 20
                        },
                        new
                        {
                            Id = 2,
                            AttendancePercentage = 72.200000000000003,
                            AttendedClasses = 13,
                            CourseCode = "CSE-4102",
                            CourseId = 2,
                            CourseName = "Machine Learning",
                            Status = 1,
                            StudentId = 1,
                            TotalClasses = 18
                        },
                        new
                        {
                            Id = 3,
                            AttendancePercentage = 100.0,
                            AttendedClasses = 16,
                            CourseCode = "CSE-4103",
                            CourseId = 3,
                            CourseName = "Cloud Computing",
                            Status = 0,
                            StudentId = 1,
                            TotalClasses = 16
                        },
                        new
                        {
                            Id = 4,
                            AttendancePercentage = 60.0,
                            AttendedClasses = 12,
                            CourseCode = "CSE-4104",
                            CourseId = 4,
                            CourseName = "Operating Systems",
                            Status = 2,
                            StudentId = 1,
                            TotalClasses = 20
                        });
                });

            modelBuilder.Entity("StudentPortalApi.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EnrolledStudents")
                        .HasColumnType("int");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Syllabus")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "CSE-4101",
                            Credits = 3,
                            Description = "Design patterns, architecture, and best practices",
                            EnrolledStudents = 45,
                            InstructorId = 1,
                            MaxCapacity = 50,
                            Name = "Advanced Software Engineering",
                            Semester = "fall-2025",
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            Code = "CSE-4102",
                            Credits = 4,
                            Description = "Introduction to ML algorithms and applications",
                            EnrolledStudents = 38,
                            InstructorId = 2,
                            MaxCapacity = 40,
                            Name = "Machine Learning",
                            Semester = "fall-2025",
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            Code = "CSE-4103",
                            Credits = 3,
                            Description = "Cloud infrastructure, services, and deployment",
                            EnrolledStudents = 42,
                            InstructorId = 3,
                            MaxCapacity = 45,
                            Name = "Cloud Computing",
                            Semester = "fall-2025",
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            Code = "CSE-4104",
                            Credits = 3,
                            Description = "OS concepts, process management, memory management, and file systems",
                            EnrolledStudents = 35,
                            InstructorId = 4,
                            MaxCapacity = 40,
                            Name = "Operating Systems",
                            Semester = "fall-2025",
                            Status = 0
                        });
                });

            modelBuilder.Entity("StudentPortalApi.Models.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<double>("GradePoints")
                        .HasColumnType("float");

                    b.Property<int>("LetterGrade")
                        .HasColumnType("int");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<double>("TotalScore")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseCode = "CSE-4101",
                            CourseId = 1,
                            CourseName = "Advanced Software Engineering",
                            Credits = 3,
                            GradePoints = 4.0,
                            LetterGrade = 1,
                            Semester = "fall-2025",
                            StudentId = 1,
                            TotalScore = 90.0
                        });
                });

            modelBuilder.Entity("StudentPortalApi.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Department");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.Property<string>("OfficeHours")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("OfficeHours");

                    b.HasKey("Id");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "Computer Science",
                            Email = "j.seetohul@university.mu",
                            Name = "Dr. J Seetohul",
                            OfficeHours = "Mon/Wed 2-4 PM"
                        },
                        new
                        {
                            Id = 2,
                            Department = "Computer Science",
                            Email = "prof.jesus@university.mu",
                            Name = "Prof. Jesus",
                            OfficeHours = "Tue/Thu 1-3 PM"
                        },
                        new
                        {
                            Id = 3,
                            Department = "Computer Science",
                            Email = "jean.melon@university.mu",
                            Name = "Dr. Jean Melon",
                            OfficeHours = "Wed/Fri 10-12 PM"
                        },
                        new
                        {
                            Id = 4,
                            Department = "Computer Science",
                            Email = "g.sathan@university.mu",
                            Name = "Mr G Sathan",
                            OfficeHours = "Mon/Thu 3-5 PM"
                        });
                });

            modelBuilder.Entity("AttendanceRecord", b =>
                {
                    b.HasOne("StudentPortalApi.Models.Attendance", "Attendance")
                        .WithMany("Records")
                        .HasForeignKey("AttendanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attendance");
                });

            modelBuilder.Entity("CourseSchedule", b =>
                {
                    b.HasOne("StudentPortalApi.Models.Course", "Course")
                        .WithMany("Schedule")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("StudentPortalApi.Models.Address", b =>
                {
                    b.HasOne("Student", "Student")
                        .WithOne("Address")
                        .HasForeignKey("StudentPortalApi.Models.Address", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentPortalApi.Models.Assignment", b =>
                {
                    b.HasOne("StudentPortalApi.Models.Grade", "Grade")
                        .WithMany("Assignments")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("StudentPortalApi.Models.Course", b =>
                {
                    b.HasOne("StudentPortalApi.Models.Instructor", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("StudentPortalApi.Models.Grade", b =>
                {
                    b.HasOne("StudentPortalApi.Models.Course", "Course")
                        .WithMany("Grades")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Student", b =>
                {
                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Grades");
                });

            modelBuilder.Entity("StudentPortalApi.Models.Attendance", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("StudentPortalApi.Models.Course", b =>
                {
                    b.Navigation("Grades");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("StudentPortalApi.Models.Grade", b =>
                {
                    b.Navigation("Assignments");
                });
#pragma warning restore 612, 618
        }
    }
}
